### ISSUE TITLE
Support for "weave attach"

### ISSUE THREAD

**Issue by prakashrj** [binocarlos/powerstrip-weave#12]
We have 3 different subnets in our environment. dmz, app and database. We were able to create the environment with a sequence of "weave run" and "weave attach" commands. It will be ideal, if "weave attach" commands can be avoided by enhancing "weave run" to support multiple CIDRS. But, I am filing this issue, because it was suggested on [weavenetwork](https://botbot.me/freenode/weavenetwork/2015-03-17/?msg=34404225&page=2) irc channel that it can be solved in powerstrip-weave.

@rade also created an issue on weave. 
zettio/weave#467

**Comment by prakashrj** [comment]
https://github.com/zettio/weave/issues/467

**Comment by binocarlos** [comment]
Hey - this is a good use case.  powerstrip-weave currently used weave attach in the POST hook after the container starts.  It's a reasonable assumption that if the WEAVE_CIDR env variable is a comma separated list then weave attach could be called multiple times with each subnet.

I will take a look at this the start of next week.

**Comment by binocarlos** [comment]
@prakashrj I've just updated powerstrip-weave so you can use multiple IP addresses in the WEAVE_CIDR environment variable.

You separate the values using a comma - here is an example:

```bash
$ docker run -d --name mysql \
    -e WEAVE_CIDR=10.255.0.1/8,10.255.60.78/24 \
    -e MYSQL_ROOT_PASSWORD=mysecretpassword \
    mysql
```

In the example above - the mysql would be run with `weave attach 10.255.0.1/8` **and** `weave attach 10.255.60.78/24`

Let me know if this is working for you - there are tests for it :-)

**Comment by prakashrj** [comment]
@sbhaskaran Can you please test this change too?

**Comment by sbhaskaran** [comment]
tested and it works good. @prakashrj  Thanks @binocarlos

**Comment by binocarlos** [comment]
Closing - please re-open if anything crops up
